title: Akoska's Blog (New)
email: ""
baseurl: "/blog"
url: ""

# Use default minima theme for a clean look
theme: minima

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed

# Include posts from the existing docs folder
collections:
  posts:
    output: true

# Tell Jekyll to also look in the parent docs folder for content
include:
  - _posts
