title: Akoska's Blog
baseurl: /blog # the base path to your site
url: ""

kramdown:
  hard_wrap: true

plugins:
  - jekyll-sitemap
  - jekyll-feed

# Ensure posts use the custom post layout by default (no external theme)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"